[theme]
# Força o tema escuro como base
base = "dark"

# Cor primária (Fica branco/cinza claro quando clica nas coisas)
primaryColor = "#ffffff" 

# Cor de fundo principal da página (O fundo escuro minimalista)
backgroundColor = "#0a0a0a"

# Cor de fundo secundária (O cinza escuro para a caixa de digitação)
secondaryBackgroundColor = "#212121"

# Cor do texto principal
textColor = "#ffffff"

# Fonte padrão do sistema
font = "sans serif"
